use crate::paycheque::PaychequeListResponseEntry;
use facet::Facet;

#[derive(Facet)]
#[facet(rename_all = "camelCase")]
pub struct PaychequeShowResponse {
    pub full_name: String,
    pub pri: String,
    pub single_paycheque: PaychequeListResponseEntry,
    pub earning_balances: Vec<EarningBalance>,
    pub tax_balances: Vec<TaxBalance>,
    pub deduction_balances: Vec<DeductionBalance>,
    pub paycheque_earnings: Vec<PaychequeEarning>,
    pub paycheque_other_earnings: Vec<PaychequeOtherEarning>,
    pub paycheque_taxes: Vec<PaychequeTax>,
    pub paycheque_deductions: Vec<PaychequeDeduction>,
}

#[derive(Facet)]
#[facet(rename_all = "camelCase")]
pub struct EarningBalance {
    pub company: String,
    pub balance_id: String,
    pub balance_year: String,
    pub wage_loss_replacement_plan: String,
    pub province: String,
    pub balance_quarter: String,
    pub balance_period: String,
    pub record_id: String,
    pub special_earning_balance: String,
    pub earning_code: String,
    pub earning_code_en: String,
    pub earning_code_fr: String,
    pub hours_year_to_date: String,
    pub hours_quarter_to_date: String,
    pub hours_month_to_date: String,
    pub gross_earning_year_to_date: String,
    pub gross_earning_quarter_to_date: String,
    pub gross_earning_month_to_date: String,
    #[facet(rename = "subjectCIT")]
    pub subject_cit: String,
    pub add_to_gross: String,
}

#[derive(Facet)]
#[facet(rename_all = "camelCase")]
pub struct TaxBalance {
    pub company: String,
    pub balance_id: String,
    pub balance_year: String,
    pub wage_loss_plan: String,
    pub province: String,
    pub balance_quarter: String,
    pub balance_period: String,
    pub canadian_tax_class: String,
    pub canadian_tax_class_en: String,
    pub canadian_tax_class_fr: String,
    pub no_limit_gross_year_to_date: String,
    pub no_limit_gross_quarter_to_date: String,
    pub no_limit_gross_month_to_date: String,
    pub taxable_gross_year_to_date: String,
    pub taxable_gross_quarter_to_date: String,
    pub taxable_gross_month_to_date: String,
    pub tax_year_to_date: String,
    pub tax_quarter_to_date: String,
    pub tax_month_to_date: String,
}
#[derive(Facet)]
#[facet(rename_all = "camelCase")]
pub struct DeductionBalance {
    pub balance_id: String,
    pub balance_year: String,
    pub wage_loss_replacement_plan: String,
    pub province: String,
    pub balance_quarter: String,
    pub balance_period: String,
    pub benefit_record_number: String,
    pub plan_type: String,
    pub benefit_plan: String,
    pub deduction_code: String,
    pub deduction_code_en: String,
    pub deduction_code_fr: String,
    pub deduction_classification: String,
    pub sales_tax_type: String,
    pub company: String,
    pub deduction_balance_year_to_date: String,
    pub deduction_balance_quarter_to_date: String,
    pub deduction_balance_month_to_date: String,
}

#[derive(Facet)]
#[facet(rename_all = "camelCase")]
pub struct PaychequeEarning {
    pub record_id: String,
    pub earnings_begin_date: String,
    pub earnings_end_date: String,
    pub earnings_begin_date_number: String,
    pub earnings_begin_date_unformatted: String,
    pub earnings_end_date_unformatted: String,
    pub ok_to_pay: String,
    pub earning_code_regular_hours: String,
    pub earning_code_overtime_hours: String,
    pub regular_pay_hours: String,
    pub regular_hours: String,
    pub overtime_hours: String,
    pub regular_hourly_earnings: String,
    pub overtime_hourly_earnings: String,
    pub earning_code: String,
    pub regular_pay: String,
    pub regular_earnings: String,
    pub regular_earning_hours: String,
    pub deduction_taken: String,
    pub deduction_subset_id: String,
    pub seperate_check_number: String,
    pub benefit_record_number: String,
    pub additional_pay_reason: String,
    pub disable_direct_deposit: String,
    pub gross_up: String,
    pub pay_line_calculation_status: String,
    pub job_pay: String,
    pub single_cheque_use: String,
    pub combination_code: String,
    pub general_ledger_pay_type: String,
    pub department_id: String,
    pub job_code: String,
    pub position_number: String,
    pub regular_shift: String,
    pub shift_differential_rate: String,
    pub flsa_rate: String,
    pub rate_used: String,
    pub rate_used_formatted_en: String,
    pub rate_used_formatted_fr: String,
    pub flsa_required: String,
    pub general_deduction_taken: String,
    pub general_deduction_subset: String,
    pub state: String,
    pub locality: String,
    pub pay_frequency: String,
    pub tax_periods: String,
    pub additional_taxes: String,
    pub override_hourly_rate_indicator: String,
    pub time_and_labor_source: String,
    pub pay_sheet_source: String,
    pub business_unit: String,
    pub ei_prior_period_correction: String,
    pub compensation_rate_regular: String,
    pub compensation_rate_overtime: String,
    pub compensation_rate_regular_used: String,
    pub compensation_rate_overtime_used: String,
    pub fica_status_employee: String,
    pub annual_tax_periods: String,
    pub flsa_end_date: String,
    pub original_paygroup: String,
    pub flsa_status: String,
    pub xref_number: String,
    pub union_code: String,
    pub benefit_deduction_status: String,
    pub general_deduction_status: String,
    pub contract_number: String,
    pub contract_sequence: String,
    pub pay_group: String,
    pub pay_period_end_date: String,
    pub off_cycle: String,
    pub page_number: String,
    pub line_number: String,
    pub tax_method: String,
    pub net_claim_amount: String,
    pub special_letters: String,
    pub additional_amount: String,
    pub additional_percentage: String,
    pub qit_net_claim: String,
    pub qit_special_letters: String,
    pub qit_additional_percentage: String,
    pub qit_additional_amount: String,
    pub cit_claim_amount: String,
    pub subject_cit: String,
    pub o_tsubject_cit: String,
    pub o_tearning_code_en: String,
    pub o_tearning_code_fr: String,
    pub earning_code_en: String,
    pub earning_code_fr: String,
    pub add_to_gross: String,
}

#[derive(Facet)]
#[facet(rename_all = "camelCase")]
pub struct PaychequeOtherEarning {
    pub earning_code: String,
    pub earning_code_en: String,
    pub earning_code_fr: String,
    pub rate_used: String,
    pub rate_used_formatted_en: String,
    pub rate_used_formatted_fr: String,
    pub job_pay: String,
    pub regular_earning_hours: String,
    pub regular_earnings: String,
    pub other_earnings: String,
    pub add_to_gross: String,
    pub tax_method: String,
    pub additional_pay_line_number: String,
    pub seperate_check_number: String,
    pub additional_pay_sequence_number: String,
    pub time_and_labor_source: String,
    pub compensation_rate_code: String,
    pub compensation_rate: String,
    pub compensation_rate_regular_used: String,
    pub hours_distribution: String,
    pub xref_number: String,
    pub expense_document_id: String,
    pub expense_document_type: String,
    pub expense_line_number: String,
    pub currency_code: String,
    pub variable_compensation_plan: String,
    pub payout_period_id: String,
    pub group_id: String,
    pub applicant_id: String,
    pub award_date: String,
    pub e_recruit_status: String,
    pub sim_sequence_number: String,
    pub paysheet_update_source: String,
    pub retro_pay_sequence_number: String,
    pub earnings_end_date: String,
    pub earnings_begin_date: String,
    pub earnings_end_date_unformatted: String,
    pub earnings_begin_date_unformatted: String,
    pub earnings_begin_date_number: String,
    pub pay_group: String,
    pub pay_period_end_date: String,
    pub off_cycle: String,
    pub page_number: String,
    pub line_number: String,
    pub empl_id: String,
    pub record_id: String,
    pub subject_cit: String,
}

#[derive(Facet)]
#[facet(rename_all = "camelCase")]
pub struct PaychequeTax {
    pub pay_group: String,
    pub pay_period_end_date: String,
    pub off_cycle: String,
    pub page_number: String,
    pub line_number: String,
    pub seperate_check_number: String,
    pub paycheck_number: String,
    pub empl_id: String,
    pub empl_record: String,
    pub province: String,
    pub canadian_tax_class: String,
    pub canadian_tax_class_fr: String,
    pub canadian_tax_class_en: String,
    pub wage_loss_replacement_plan: String,
    pub current_no_limit_gross: String,
    pub current_taxable_gross: String,
    pub current_tax: String,
    pub tax_not_taken: String,
    pub el_employer_rate: String,
    pub ap_status: String,
}

#[derive(Facet)]
#[facet(rename_all = "camelCase")]
pub struct PaychequeDeduction {
    pub record_id: String,
    pub cheque_number: String,
    pub seperate_check_number: String,
    pub pay_period_end_date: String,
    pub pay_group: String,
    pub off_cycle: String,
    pub page_number: String,
    pub line_number: String,
    pub benefit_record_number: String,
    pub plan_type: String,
    pub benefit_plan: String,
    pub deduction_code: String,
    pub deduction_code_en: String,
    pub deduction_code_fr: String,
    pub deduction_classification: String,
    pub sales_tax_type: String,
    pub current_deduction: String,
    pub current_deduction_pay_back: String,
    pub current_deduction_refund: String,
    pub deduction_not_taken: String,
    pub reason_not_taken: String,
    pub calculated_base: String,
    pub ap_status: String,
    pub empl_id: String,
}
